sudo: required
services:
- docker
env:
  global:
  - DOCKERHUB_USERNAME=kspckanbuilder
  - secure: nYqcReYlGtNY9X+yH6RboyzFJPk9C3AExjmCrSMg/kjN7PXYQ5N79IUAtY66K9gkduoKFyoAXN2BlHMThb0BPONuKQpXOi/e/L0oppbQ4MI1XVZJBoajLD5slkfoVy1C0/0urdnHKM1YhQUBz/R0nNLgu3wN8FoLWI4E3DV2bjUwfNF7IwdSibirpJa5fgjVE/zb2sEuTDfS1r0pLIR8Vtw5KB3LdbariMO71TqrM8C2Ibd5rey5NdRTrrzX+inpQbBE6ZdWUm08umsSdYQ0Sb5D4A7CYl8AnLJFTJBfeG8VT1jMTpo5Sy3f8zWFhioBL7lWenmOJdlO7pJrGCC+AEBHRWKjI7PqwoPOJjBmJeTC0BZX8w+sn4nAtfsHplAQRGUbrsX7B51DCCrjBFuvdNnb5faQs6GYjdaRe680ci40DtR/qdIvxlWFNq/6tWjetLnugb2WNey5bDjm42QxMYDXOC+SVXLlEpToNlDeALmxdilf7NLW7tuPbMzJAHG5gOJUXMYFhH1BHBZGyQnvpIN1bpj6UaRcX+IjBfCBAcn+VM0VSbiWFPanY8roFUin1gMZ2nvcP30oMGjE1y4bEQKtX0GFy01cWgpdPwtoJzNWJmz9B+VSV9R3XO2HBkoPO0AiyKSTcqNBN8r5RMItT0c9TGwmqrBUZZZ6z5yBVuM=
  - AWS_DEFAULT_REGION=us-west-2
  - AWS_ACCESS_KEY_ID=AKIAZA4K6RW77XSCAMI2
  - secure: "J8jKREaTO1YVa2NmLaJU7sw1fWoiBrnPWjfUb2VwCUy7KNzAD6OJU1BjaLQpCPPZajZLKWNGgLyALgyMLb0dYRKMU2P3gG75kWN78P94MgIn3srUgt2GiBcZr82OegXrI3f2JPH6A5/j7qsEkRntUDFui5jvKv4JHTzDmREZMbYFWuS6bZNzuFenbBdc0DEF0r3sYupY8lqZgaL5fMvz32VFEaTkZ8Y+zE1R5xAv32DWddL0e+2ax8Hp5kBVehuq8xhsoDsYAlURpxCkeGH/nbLtv/PIiYkj6LjfushyQTOkPVa4E4TxUPOaNP2r4PyD9W1RJwHhe6wLkF0gwmX8jPGJjUMfxIbE8iU3+pkOZLxza+joPNbwkoo7ffMqdpkSB2TTTSItIekaVkzT6HYNgUQq+PqdYQiktgbX/I8TUoUcsfuRHHttxszsu/h8dlHEBiTJ2BhM2Dhc3JfZsQMMrKMSbnaU4VUus+zLFvFZP/wJGfRz5ovvWHciHMN1YWJLIco0Hnz5xzSBPK9e03jgy1hmcr8R6n5zIsuulK7vGjn+xHGlxj+EzK2zzagKwsSo5mzXBRWAjFwcKkNeaYHHVUotxAxrRDauIrADfSLeHBlEOnR86Mb0khwdEhrNYkdRBMqXjfrnfb3bS9skLoHDHFzws38FMyUEp57dBqAVHbM="
before_script:
- docker pull "kspckan/netkan" || true
script:
- docker build netkan/. -t kspckan/netkan
before_deploy:
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
deploy:
  provider: script
  script: bin/push_deploy_containers.sh
  on:
    branch: master
