name: Test

on:
  - push
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - name: Install test dependencies
        working-directory: netkan
        run: pip install .[test]
      - name: force our git config
        working-directory: netkan
        run: cp .gitconfig ~/.
      - name: Run pytest
        working-directory: netkan
        run: pytest -v
